version: "3.8"
services:
    # MySQL database container
    garage_db:
        image: mysql:8.4
        container_name: garage_db
        command: --mysql-native-password=ON
        restart: always
        environment:
            MYSQL_DATABASE: garage
            MYSQL_ROOT_PASSWORD: garage_pwd
            MYSQL_USER: garage_user
            MYSQL_PASSWORD: garage_pwd
        ports:
            - "3306:3306"
        networks:
            - garage
    
    # phpMyAdmin container
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: garage_phpmyadmin
        restart: always
        depends_on:
            - garage_db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: garage_db
        networks:
            - garage

    # Symfony Apache project container (Back-end)
    backend:
        build: ./
        container_name: garage_backend
        ports:
          - "8000:8000"
        volumes:
            - .:/var/www/html  # Symfony root directory, adjusted based on your structure
        restart: always
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1
            DATABASE_URL: "mysql://garage_user:garage_pwd@garage_db:3306/garage?serverVersion=8.3.0&charset=utf8mb4"
        depends_on:
            -  garage_db # Ensure MySQL is started before Symfony
        command: bash -c "/usr/local/bin/docker-entrypoint.sh"
        networks:
            - garage

networks:
    garage:

